"resources"
{
"maps/bt_museum_v1.bsp" "file"
"maps/bt_museum_v1.res" "file"
"maps/bt_museum_readme.txt" "file"


"materials/models/knochen.vmt" "file"
"materials/models/knochen.vtf" "file"

"models/models/brachio_skull2_gross.mdl" "file"
"models/models/brachio_skull2_gross.dx80.vtx" "file"
"models/models/brachio_skull2_gross.dx90.vtx" "file"
"models/models/brachio_skull2_gross.phy" "file"
"models/models/brachio_skull2_gross.sw.vtx" "file"
"models/models/brachio_skull2_gross.vvd" "file"
"models/models/brachio_skull2_gross.xbox.vtx" "file"

"models/models/brachio_hals_gross.mdl" "file"
"models/models/brachio_hals_gross.dx80.vtx" "file"
"models/models/brachio_hals_gross.dx90.vtx" "file"
"models/models/brachio_hals_gross.phy" "file"
"models/models/brachio_hals_gross.sw.vtx" "file"
"models/models/brachio_hals_gross.vvd" "file"
"models/models/brachio_hals_gross.xbox.vtx" "file"

"models/models/brac_beine_vorne_gross.mdl" "file"
"models/models/brac_beine_vorne_gross.dx80.vtx" "file"
"models/models/brac_beine_vorne_gross.dx90.vtx" "file"
"models/models/brac_beine_vorne_gross.phy" "file"
"models/models/brac_beine_vorne_gross.sw.vtx" "file"
"models/models/brac_beine_vorne_gross.vvd" "file"
"models/models/brac_beine_vorne_gross.xbox.vtx" "file"

"models/models/brachio_rippen_gross.mdl" "file"
"models/models/brachio_rippen_gross.dx80.vtx" "file"
"models/models/brachio_rippen_gross.dx90.vtx" "file"
"models/models/brachio_rippen_gross.phy" "file"
"models/models/brachio_rippen_gross.sw.vtx" "file"
"models/models/brachio_rippen_gross.vvd" "file"
"models/models/brachio_rippen_gross.xbox.vtx" "file"

"models/models/brac_mittel_wirbel_gross.mdl" "file"
"models/models/brac_mittel_wirbel_gross.dx80.vtx" "file"
"models/models/brac_mittel_wirbel_gross.dx90.vtx" "file"
"models/models/brac_mittel_wirbel_gross.phy" "file"
"models/models/brac_mittel_wirbel_gross.sw.vtx" "file"
"models/models/brac_mittel_wirbel_gross.vvd" "file"
"models/models/brac_mittel_wirbel_gross.xbox.vtx" "file"

"models/models/brachio_wirbel_2.mdl" "file"
"models/models/brachio_wirbel_2.dx80.vtx" "file"
"models/models/brachio_wirbel_2.dx90.vtx" "file"
"models/models/brachio_wirbel_2.phy" "file"
"models/models/brachio_wirbel_2.sw.vtx" "file"
"models/models/brachio_wirbel_2.vvd" "file"
"models/models/brachio_wirbel_2.xbox.vtx" "file"

"models/models/brachio_wirbel_3.mdl" "file"
"models/models/brachio_wirbel_3.dx80.vtx" "file"
"models/models/brachio_wirbel_3.dx90.vtx" "file"
"models/models/brachio_wirbel_3.phy" "file"
"models/models/brachio_wirbel_3.sw.vtx" "file"
"models/models/brachio_wirbel_3.vvd" "file"
"models/models/brachio_wirbel_3.xbox.vtx" "file"

"models/models/brachio_wirbel_4.mdl" "file"
"models/models/brachio_wirbel_4.dx80.vtx" "file"
"models/models/brachio_wirbel_4.dx90.vtx" "file"
"models/models/brachio_wirbel_4.phy" "file"
"models/models/brachio_wirbel_4.sw.vtx" "file"
"models/models/brachio_wirbel_4.vvd" "file"
"models/models/brachio_wirbel_4.xbox.vtx" "file"

"models/models/brachio_wirbel_5.mdl" "file"
"models/models/brachio_wirbel_5.dx80.vtx" "file"
"models/models/brachio_wirbel_5.dx90.vtx" "file"
"models/models/brachio_wirbel_5.phy" "file"
"models/models/brachio_wirbel_5.sw.vtx" "file"
"models/models/brachio_wirbel_5.vvd" "file"
"models/models/brachio_wirbel_5.xbox.vtx" "file"

"models/models/brachio_wirbel_6.mdl" "file"
"models/models/brachio_wirbel_6.dx80.vtx" "file"
"models/models/brachio_wirbel_6.dx90.vtx" "file"
"models/models/brachio_wirbel_6.phy" "file"
"models/models/brachio_wirbel_6.sw.vtx" "file"
"models/models/brachio_wirbel_6.vvd" "file"
"models/models/brachio_wirbel_6.xbox.vtx" "file"

"models/models/brachio_wirbel_7.mdl" "file"
"models/models/brachio_wirbel_7.dx80.vtx" "file"
"models/models/brachio_wirbel_7.dx90.vtx" "file"
"models/models/brachio_wirbel_7.phy" "file"
"models/models/brachio_wirbel_7.sw.vtx" "file"
"models/models/brachio_wirbel_7.vvd" "file"
"models/models/brachio_wirbel_7.xbox.vtx" "file"

"models/models/brac_beine_hinten_gross.mdl" "file"
"models/models/brac_beine_hinten_gross.dx80.vtx" "file"
"models/models/brac_beine_hinten_gross.dx90.vtx" "file"
"models/models/brac_beine_hinten_gross.phy" "file"
"models/models/brac_beine_hinten_gross.sw.vtx" "file"
"models/models/brac_beine_hinten_gross.vvd" "file"
"models/models/brac_beine_hinten_gross.xbox.vtx" "file"

"models/models/brachio_tail1.mdl" "file"
"models/models/brachio_tail1.dx80.vtx" "file"
"models/models/brachio_tail1.dx90.vtx" "file"
"models/models/brachio_tail1.phy" "file"
"models/models/brachio_tail1.sw.vtx" "file"
"models/models/brachio_tail1.vvd" "file"
"models/models/brachio_tail1.xbox.vtx" "file"

"models/models/brachio_tail2.mdl" "file"
"models/models/brachio_tail2.dx80.vtx" "file"
"models/models/brachio_tail2.dx90.vtx" "file"
"models/models/brachio_tail2.phy" "file"
"models/models/brachio_tail2.sw.vtx" "file"
"models/models/brachio_tail2.vvd" "file"
"models/models/brachio_tail2.xbox.vtx" "file"

"models/models/brachio_tail3.mdl" "file"
"models/models/brachio_tail3.dx80.vtx" "file"
"models/models/brachio_tail3.dx90.vtx" "file"
"models/models/brachio_tail3.phy" "file"
"models/models/brachio_tail3.sw.vtx" "file"
"models/models/brachio_tail3.vvd" "file"
"models/models/brachio_tail3.xbox.vtx" "file"

"models/models/brachio_tail4.mdl" "file"
"models/models/brachio_tail4.dx80.vtx" "file"
"models/models/brachio_tail4.dx90.vtx" "file"
"models/models/brachio_tail4.phy" "file"
"models/models/brachio_tail4.sw.vtx" "file"
"models/models/brachio_tail4.vvd" "file"
"models/models/brachio_tail4.xbox.vtx" "file"

"models/models/brachio_tail5.mdl" "file"
"models/models/brachio_tail5.dx80.vtx" "file"
"models/models/brachio_tail5.dx90.vtx" "file"
"models/models/brachio_tail5.phy" "file"
"models/models/brachio_tail5.sw.vtx" "file"
"models/models/brachio_tail5.vvd" "file"
"models/models/brachio_tail5.xbox.vtx" "file"

"models/models/brachio_tail6.mdl" "file"
"models/models/brachio_tail6.dx80.vtx" "file"
"models/models/brachio_tail6.dx90.vtx" "file"
"models/models/brachio_tail6.phy" "file"
"models/models/brachio_tail6.sw.vtx" "file"
"models/models/brachio_tail6.vvd" "file"
"models/models/brachio_tail6.xbox.vtx" "file"

"models/models/brachio_tail7.mdl" "file"
"models/models/brachio_tail7.dx80.vtx" "file"
"models/models/brachio_tail7.dx90.vtx" "file"
"models/models/brachio_tail7.phy" "file"
"models/models/brachio_tail7.sw.vtx" "file"
"models/models/brachio_tail7.vvd" "file"
"models/models/brachio_tail7.xbox.vtx" "file"

"models/models/brachio_tail8.mdl" "file"
"models/models/brachio_tail8.dx80.vtx" "file"
"models/models/brachio_tail8.dx90.vtx" "file"
"models/models/brachio_tail8.phy" "file"
"models/models/brachio_tail8.sw.vtx" "file"
"models/models/brachio_tail8.vvd" "file"
"models/models/brachio_tail8.xbox.vtx" "file"

"models/models/brachio_tail9.mdl" "file"
"models/models/brachio_tail9.dx80.vtx" "file"
"models/models/brachio_tail9.dx90.vtx" "file"
"models/models/brachio_tail9.phy" "file"
"models/models/brachio_tail9.sw.vtx" "file"
"models/models/brachio_tail9.vvd" "file"
"models/models/brachio_tail9.xbox.vtx" "file"

"models/models/brachio_tail10.mdl" "file"
"models/models/brachio_tail10.dx80.vtx" "file"
"models/models/brachio_tail10.dx90.vtx" "file"
"models/models/brachio_tail10.phy" "file"
"models/models/brachio_tail10.sw.vtx" "file"
"models/models/brachio_tail10.vvd" "file"
"models/models/brachio_tail10.xbox.vtx" "file"

"models/models/brachio_tail11.mdl" "file"
"models/models/brachio_tail11.dx80.vtx" "file"
"models/models/brachio_tail11.dx90.vtx" "file"
"models/models/brachio_tail11.phy" "file"
"models/models/brachio_tail11.sw.vtx" "file"
"models/models/brachio_tail11.vvd" "file"
"models/models/brachio_tail11.xbox.vtx" "file"
}